### ISSUE TITLE
Not correct generated scheme

### ISSUE THREAD

**Issue by gammapopolam** [ad-freiburg/loom#8]
Hello! Loom is not working correctly on my machine. Generated scheme for Stuttgart does not match the one attached in your examples.
I rebuilt project several times, checked the versions of the libraries, but this does not fix the error and I do not understand what the problem is. Can you please tell me how to solve the problem? Uploaded the scheme below
https://disk.yandex.ru/d/zaMvVtyPAjsg6g

**Comment by patrickbr** [comment]
This is really strange - I will investigate this asap. What command line parameters are you using?

**Comment by patrickbr** [comment]
I just tested this with the latest master and the following command:

    cat ../examples/stuttgart.json | ./transitmap > test.svg

The resulting SVG looks as expected. What machine / OS are you using?

**Comment by gammapopolam** [comment]
ubuntu 22.04, 8gb RAM, gcc 11.8.3, cmake 3.22.1, GNU make 4.3

**Comment by patrickbr** [comment]
Can you give me the output of

`$ git rev-parse HEAD`

in your local repo?

**Comment by gammapopolam** [comment]
db046a5ae0f553e66b62dd9eab8549624fa9a169, did it after rebuilding

**Comment by patrickbr** [comment]
Is it possible that you did a rebuild, but forgot to run

    make install

?

To check this, can you switch into your build repository and try running the binaries there directly?

    cd build
    cat ../examples/stuttgart.json | ./loom | ./transitmap > test.svg

**Comment by gammapopolam** [comment]
i wrote `make install` too. tried running the binaries directly, but the result is the same

**Comment by patrickbr** [comment]
Ok, I was able to reproduce this, thank you very much for pointing out this issue. Will fix asap.

**Comment by gammapopolam** [comment]
thanks for the reply! also, what could be the reasons why gtfs2graph can take up more than 4 gigabytes of RAM? I tried to build a graph for my example, but the process freezes

**Comment by patrickbr** [comment]
What GTFS feed are you using?

**Comment by gammapopolam** [comment]
I generated my own feed with shapes from pfaedle and tried to make the scheme. when I'm trying to generate a graph, `topo` takes up more than 4 GB of RAM so the system terminate task

**Comment by patrickbr** [comment]
And what was the input feed to pfaedle? Was it a large feed or does it have lines covering a large distance?

**Comment by gammapopolam** [comment]
This feed is for quite small town and it appears valid and true in QGIS, link to the feed is below
https://disk.yandex.ru/d/RbOQQczHh6eGdw

**Comment by patrickbr** [comment]
There were two problems:

1. There was a typo introduced a few commits back during the development of the MvtRenderer, which lead to wrong offsets being taken in the SVG Renderer.
2. We switched from Web Mercator to WGS84-coordinates for the GeoJSON-outputs a few months ago, to be compatible to the GeoJSON standard. However, this was not enabled for `gtfs2graph`. Feeding Web Mercator coordinates generated by `gtfs2graph` into `topo` then lead to web mercator coordinates being interpreted as WGS84, leading to enourmously large line segments. Sampling these with the default sampling rate quickly used up tens of gigabytes of RAM.

Both issues are fixed in the current master :)

Thanks again for noticing these issues!

**Comment by gammapopolam** [comment]
Thank you! So now examples works well. The scheme based on my feed generates bad but it's look like there is a lot of issues with validation and geometry.
